build_image: shippableimages/ubuntu1404_base
cache: true
before_install:
  - shippable_retry sudo apt-get -y -qq update
install:
  - shippable_retry sudo apt-get -y -qq install --no-install-recommends qt5-default qtbase5-private-dev libqt5webkit5-dev libarchive-dev
script:
  - qmake
  - make
