# https://snapcraft.io/docs
name: zeal
base: core24
adopt-info: zeal
contact:
  - https://go.zealdocs.org/l/contact
  - support@zealdocs.org
grade: stable
confinement: strict

platforms:
  amd64:
  arm64:

lint:
  ignore:
    - library:
        - usr/lib/**/libicuio.so.*
        - usr/lib/**/libicutest.so.*
        - usr/lib/**/libicutu.so.*

apps:
  zeal:
    command: usr/bin/zeal
    common-id: org.zealdocs.zeal
    extensions: [kde-neon-6]
    plugs:
      - home
      - network
      - opengl
      - browser-support
    environment:
      # Chromium's sandbox conflicts with snap's confinement.
      QTWEBENGINE_DISABLE_SANDBOX: "1"

parts:
  zeal:
    plugin: cmake
    source: .
    parse-info:
      - usr/share/metainfo/org.zealdocs.zeal.appdata.xml
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
    build-packages:
      - extra-cmake-modules
      - libarchive-dev
      - libgl1-mesa-dev
      - libsqlite3-dev
      - libvulkan-dev
      - libxcb-keysyms1-dev
    stage-packages:
      - libarchive13t64
      - libsqlite3-0
      - libxcb-keysyms1
    override-build: |
      craftctl default
      craftctl set version=$(cat ${CRAFT_PART_BUILD}/zeal_version)
