name: Release

on:
  push:
    tags:
      - "v*.*.*"

# Required for creating GitHub release.
permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows Server 2022 / Qt 6
            os: windows-2022
            arch: win64_msvc2022_64
            qt_modules: >-
              qtpositioning
              qtwebchannel
              qtwebengine
            qt_version: "6.10.2"
            configurePreset: ninja-multi-vcpkg
            buildPreset: ninja-multi-vcpkg-release
          - name: Windows Server 2022 / Qt 6 / Portable
            os: windows-2022
            arch: win64_msvc2022_64
            qt_modules: >-
              qtpositioning
              qtwebchannel
              qtwebengine
            qt_version: "6.10.2"
            configurePreset: ninja-multi-vcpkg-portable
            buildPreset: ninja-multi-vcpkg-portable-release

    env:
      VCPKG_BUILD_TYPE: release
      VCPKG_DEFAULT_TRIPLET: x64-windows
      ZEAL_RELEASE_BUILD: ON

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Prepare vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/.vcpkg

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          arch: ${{ matrix.config.arch }}
          modules: ${{ matrix.config.qt_modules }}
          version: ${{ matrix.config.qt_version }}
          cache: true

      - name: Configure & Build
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ matrix.config.configurePreset }}
          buildPreset: ${{ matrix.config.buildPreset }}
          configurePresetAdditionalArgs: "['-DVCPKG_DISABLE_COMPILER_TRACKING=ON']"

      - name: Retrieve Application Version
        run: |
          $zeal_version = Get-Content build/${{ matrix.config.configurePreset }}/zeal_version
          Write-Output "Zeal Version: $zeal_version"
          "ZEAL_VERSION=$zeal_version" >> $env:GITHUB_ENV

      - name: Package
        run: cmake --build build --preset ${{ matrix.config.buildPreset }} --target package
        env:
          CODESIGN_CERTIFICATE_BASE64: ${{ secrets.CODESIGN_CERTIFICATE_BASE64 }}
          CODESIGN_PASSWORD: ${{ secrets.CODESIGN_PASSWORD }}

      - name: Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          # Only upload the following artifacts:
          # - Portable 7-Zip and ZIP packages.
          # - Non-portable MSI package.
          files: |
            build/${{ matrix.config.configurePreset }}/zeal-${{ env.ZEAL_VERSION }}-portable-windows-x64.*
            build/${{ matrix.config.configurePreset }}/zeal-${{ env.ZEAL_VERSION }}-windows-x64.msi*

  build-appimage:
    name: AppImage
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get -y -qq update
          sudo apt-get -y -qq --no-install-recommends install \
            appstream \
            cmake \
            extra-cmake-modules \
            libarchive-dev \
            libfuse2t64 \
            libgl1-mesa-dev \
            libqt6opengl6-dev \
            libsqlite3-dev \
            libvulkan-dev \
            libxcb-keysyms1-dev \
            ninja-build \
            qt6-base-private-dev \
            qt6-webengine-dev \
            qt6-webengine-dev-tools

      - name: Install linuxdeploy
        run: |
          wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/1-alpha-20251107-1/linuxdeploy-x86_64.AppImage
          wget -q https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/1-alpha-20250213-1/linuxdeploy-plugin-appimage-x86_64.AppImage
          wget -q https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/1-alpha-20250213-1/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x linuxdeploy*.AppImage

      - name: Configure & Build
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr -DZEAL_RELEASE_BUILD=ON
          cmake --build build

      - name: Retrieve Application Version
        run: |
          zeal_version=$(<build/zeal_version)
          echo "Zeal Version: ${zeal_version}"
          echo "ZEAL_VERSION=${zeal_version}" >> $GITHUB_ENV

      - name: Prepare AppDir
        run: DESTDIR=${{ github.workspace }}/AppDir cmake --install build

      - name: Validate AppStream Metadata
        run: appstreamcli validate AppDir/usr/share/metainfo/org.zealdocs.zeal.appdata.xml

      - name: Set Up AppRun Hooks
        run: |
          mkdir -p AppDir/apprun-hooks
          echo 'export QTWEBENGINE_DISABLE_SANDBOX=1' > AppDir/apprun-hooks/qtwebengine.sh

      - name: Build AppImage
        run: |
          export QMAKE=$(which qmake6)
          export OUTPUT=Zeal-${{ env.ZEAL_VERSION }}-x86_64.AppImage
          export LDAI_UPDATE_INFORMATION="gh-releases-zsync|zealdocs|zeal|latest|Zeal-*x86_64.AppImage.zsync"
          ./linuxdeploy-x86_64.AppImage \
            --appdir AppDir \
            --plugin qt \
            --output appimage

      - name: Generate Digest Files
        run: for file in Zeal-*.AppImage*; do sha256sum $file > $file.sha256; done

      - name: Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          fail_on_unmatched_files: true
          files: |
            Zeal-*.AppImage*

  build-ubuntu:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Ubuntu 24.04 / Source
            os: ubuntu-24.04
            qt_packages: >-
              libgl1-mesa-dev
              libqt6opengl6-dev
              qt6-base-private-dev
              qt6-webengine-dev
              qt6-webengine-dev-tools
            configurePreset: ninja-multi
            buildPreset: ninja-multi-release

    env:
      ZEAL_RELEASE_BUILD: ON

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get -y -qq update
          sudo apt-get -y -qq --no-install-recommends install \
            cmake \
            extra-cmake-modules \
            libarchive-dev \
            libsqlite3-dev \
            libvulkan-dev \
            libxcb-keysyms1-dev \
            ninja-build \
            ${{ matrix.config.qt_packages }}

      - name: Configure & Package Source
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ matrix.config.configurePreset }}
          buildPreset: ${{ matrix.config.buildPreset }}
          buildPresetAdditionalArgs: "['--target package_source']"

      - name: Generate Changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          args: --latest
          config: .github/workflows/release/cliff.toml
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          fail_on_unmatched_files: true
          body: ${{ steps.git-cliff.outputs.content }}
          # Only upload the following artifacts:
          # - Source packages.
          files: |
            build/${{ matrix.config.configurePreset }}/zeal-*.*
