name: Release Please

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    name: Release Please
    if: github.repository == 'zealdocs/zeal'
    runs-on: ubuntu-latest

    steps:
      - name: Generate App Token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
